# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialogoption.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogOption(object):
    def setupUi(self, DialogOption):
        DialogOption.setObjectName("DialogOption")
        DialogOption.resize(505, 317)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogOption)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogOption)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.text_option_text = QtWidgets.QLineEdit(DialogOption)
        self.text_option_text.setObjectName("text_option_text")
        self.verticalLayout.addWidget(self.text_option_text)
        self.label_2 = QtWidgets.QLabel(DialogOption)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_outcomes = QtWidgets.QTableWidget(DialogOption)
        self.table_outcomes.setObjectName("table_outcomes")
        self.table_outcomes.setColumnCount(3)
        self.table_outcomes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_outcomes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outcomes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_outcomes.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.table_outcomes)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_add_outcome = QtWidgets.QToolButton(DialogOption)
        self.button_add_outcome.setMinimumSize(QtCore.QSize(25, 0))
        self.button_add_outcome.setObjectName("button_add_outcome")
        self.verticalLayout_2.addWidget(self.button_add_outcome)
        self.button_delete_outcome = QtWidgets.QToolButton(DialogOption)
        self.button_delete_outcome.setMinimumSize(QtCore.QSize(25, 0))
        self.button_delete_outcome.setObjectName("button_delete_outcome")
        self.verticalLayout_2.addWidget(self.button_delete_outcome)
        self.button_edit_outcome = QtWidgets.QToolButton(DialogOption)
        self.button_edit_outcome.setObjectName("button_edit_outcome")
        self.verticalLayout_2.addWidget(self.button_edit_outcome)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogOption)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogOption)
        self.buttonBox.accepted.connect(DialogOption.accept)
        self.buttonBox.rejected.connect(DialogOption.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogOption)

    def retranslateUi(self, DialogOption):
        _translate = QtCore.QCoreApplication.translate
        DialogOption.setWindowTitle(_translate("DialogOption", "New Event Option"))
        self.label.setText(_translate("DialogOption", "Text"))
        self.label_2.setText(_translate("DialogOption", "Outcomes"))
        item = self.table_outcomes.horizontalHeaderItem(0)
        item.setText(_translate("DialogOption", "Action"))
        item = self.table_outcomes.horizontalHeaderItem(1)
        item.setText(_translate("DialogOption", "Chance"))
        item = self.table_outcomes.horizontalHeaderItem(2)
        item.setText(_translate("DialogOption", "Text"))
        self.button_add_outcome.setText(_translate("DialogOption", "+"))
        self.button_delete_outcome.setText(_translate("DialogOption", "-"))
        self.button_edit_outcome.setText(_translate("DialogOption", "..."))
