# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialogoutcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogOutcome(object):
    def setupUi(self, DialogOutcome):
        DialogOutcome.setObjectName("DialogOutcome")
        DialogOutcome.resize(400, 389)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogOutcome)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogOutcome)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.combo_action = QtWidgets.QComboBox(DialogOutcome)
        self.combo_action.setObjectName("combo_action")
        self.combo_action.addItem("")
        self.combo_action.addItem("")
        self.combo_action.addItem("")
        self.verticalLayout.addWidget(self.combo_action)
        self.label_text = QtWidgets.QLabel(DialogOutcome)
        self.label_text.setObjectName("label_text")
        self.verticalLayout.addWidget(self.label_text)
        self.text_outcome_text = QtWidgets.QTextEdit(DialogOutcome)
        self.text_outcome_text.setObjectName("text_outcome_text")
        self.verticalLayout.addWidget(self.text_outcome_text)
        self.label_2 = QtWidgets.QLabel(DialogOutcome)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinner_chance = QtWidgets.QSpinBox(DialogOutcome)
        self.spinner_chance.setMaximum(100)
        self.spinner_chance.setObjectName("spinner_chance")
        self.verticalLayout.addWidget(self.spinner_chance)
        self.label_tags = QtWidgets.QLabel(DialogOutcome)
        self.label_tags.setObjectName("label_tags")
        self.verticalLayout.addWidget(self.label_tags)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.check_tag_common = QtWidgets.QCheckBox(DialogOutcome)
        self.check_tag_common.setObjectName("check_tag_common")
        self.gridLayout.addWidget(self.check_tag_common, 0, 0, 1, 1)
        self.check_tag_medical = QtWidgets.QCheckBox(DialogOutcome)
        self.check_tag_medical.setObjectName("check_tag_medical")
        self.gridLayout.addWidget(self.check_tag_medical, 0, 1, 1, 1)
        self.check_tag_millitary = QtWidgets.QCheckBox(DialogOutcome)
        self.check_tag_millitary.setObjectName("check_tag_millitary")
        self.gridLayout.addWidget(self.check_tag_millitary, 1, 0, 1, 1)
        self.check_tag_police = QtWidgets.QCheckBox(DialogOutcome)
        self.check_tag_police.setObjectName("check_tag_police")
        self.gridLayout.addWidget(self.check_tag_police, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_eventid = QtWidgets.QLabel(DialogOutcome)
        self.label_eventid.setObjectName("label_eventid")
        self.verticalLayout.addWidget(self.label_eventid)
        self.spinner_eventid = QtWidgets.QSpinBox(DialogOutcome)
        self.spinner_eventid.setMaximum(99999999)
        self.spinner_eventid.setObjectName("spinner_eventid")
        self.verticalLayout.addWidget(self.spinner_eventid)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogOutcome)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogOutcome)
        self.buttonBox.accepted.connect(DialogOutcome.accept)
        self.buttonBox.rejected.connect(DialogOutcome.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogOutcome)

    def retranslateUi(self, DialogOutcome):
        _translate = QtCore.QCoreApplication.translate
        DialogOutcome.setWindowTitle(_translate("DialogOutcome", "New Option Outcome"))
        self.label.setText(_translate("DialogOutcome", "Action"))
        self.combo_action.setItemText(0, _translate("DialogOutcome", "ENEMY_ENCOUNTER"))
        self.combo_action.setItemText(1, _translate("DialogOutcome", "LOOT_ROLL"))
        self.combo_action.setItemText(2, _translate("DialogOutcome", "EVENT_TRIGGER"))
        self.label_text.setText(_translate("DialogOutcome", "Text"))
        self.label_2.setText(_translate("DialogOutcome", "Chance"))
        self.label_tags.setText(_translate("DialogOutcome", "Tags"))
        self.check_tag_common.setText(_translate("DialogOutcome", "COMMON"))
        self.check_tag_medical.setText(_translate("DialogOutcome", "MEDICAL"))
        self.check_tag_millitary.setText(_translate("DialogOutcome", "MILLITARY"))
        self.check_tag_police.setText(_translate("DialogOutcome", "POLICE"))
        self.label_eventid.setText(_translate("DialogOutcome", "Event ID"))
