# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialogeffect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEffect(object):
    def setupUi(self, DialogEffect):
        DialogEffect.setObjectName("DialogEffect")
        DialogEffect.resize(400, 207)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEffect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogEffect)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.combo_effect = QtWidgets.QComboBox(DialogEffect)
        self.combo_effect.setObjectName("combo_effect")
        self.combo_effect.addItem("")
        self.combo_effect.addItem("")
        self.verticalLayout.addWidget(self.combo_effect)
        self.label_2 = QtWidgets.QLabel(DialogEffect)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.spinner_value = QtWidgets.QSpinBox(DialogEffect)
        self.spinner_value.setObjectName("spinner_value")
        self.verticalLayout.addWidget(self.spinner_value)
        self.label_duration = QtWidgets.QLabel(DialogEffect)
        self.label_duration.setToolTip("")
        self.label_duration.setObjectName("label_duration")
        self.verticalLayout.addWidget(self.label_duration)
        self.spinner_duration = QtWidgets.QSpinBox(DialogEffect)
        self.spinner_duration.setObjectName("spinner_duration")
        self.verticalLayout.addWidget(self.spinner_duration)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogEffect)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogEffect)
        self.buttonBox.accepted.connect(DialogEffect.accept)
        self.buttonBox.rejected.connect(DialogEffect.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogEffect)

    def retranslateUi(self, DialogEffect):
        _translate = QtCore.QCoreApplication.translate
        DialogEffect.setWindowTitle(_translate("DialogEffect", "Add New Effect"))
        self.label.setText(_translate("DialogEffect", "Effect"))
        self.combo_effect.setItemText(0, _translate("DialogEffect", "BURNING"))
        self.combo_effect.setItemText(1, _translate("DialogEffect", "STUNNED"))
        self.label_2.setText(_translate("DialogEffect", "Amount"))
        self.label_duration.setText(_translate("DialogEffect", "Duration"))
