# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZombieData(object):
    def setupUi(self, ZombieData):
        ZombieData.setObjectName("ZombieData")
        ZombieData.resize(839, 683)
        self.centralwidget = QtWidgets.QWidget(ZombieData)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_items = QtWidgets.QWidget()
        self.tab_items.setObjectName("tab_items")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_items)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget.addTab(self.tab_items, "")
        self.tab_enemies = QtWidgets.QWidget()
        self.tab_enemies.setObjectName("tab_enemies")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_enemies)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget.addTab(self.tab_enemies, "")
        self.tab_events = QtWidgets.QWidget()
        self.tab_events.setObjectName("tab_events")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_events)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget.addTab(self.tab_events, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        ZombieData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ZombieData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ZombieData.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ZombieData)
        self.statusbar.setObjectName("statusbar")
        ZombieData.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(ZombieData)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(ZombieData)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(ZombieData)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ZombieData)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(ZombieData)

    def retranslateUi(self, ZombieData):
        _translate = QtCore.QCoreApplication.translate
        ZombieData.setWindowTitle(_translate("ZombieData", "ZombieData"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_items), _translate("ZombieData", "Items"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_enemies), _translate("ZombieData", "Enemies"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_events), _translate("ZombieData", "Events"))
        self.menuFile.setTitle(_translate("ZombieData", "File"))
        self.actionSave.setText(_translate("ZombieData", "Save"))
        self.actionSave.setShortcut(_translate("ZombieData", "Ctrl+S"))
        self.actionLoad.setText(_translate("ZombieData", "Load"))
        self.actionExit.setText(_translate("ZombieData", "Exit"))
